### ISSUE TITLE
Declare dependency on the filter

### ISSUE THREAD

**Issue by mudrd8mz** [richardjonesnz/moodle_atto_question#1]
Even when technically the Atto button can work without it, it does not make practical sense to have the button installed without the filter. For these cases, it is recommended to declare the dependency in the filter, too.

See `$plugin->dependencies` at https://docs.moodle.org/dev/version.php

**Comment by richardjonesnz** [comment]
The button version file currently has the filter as a dependency.  However the filter can work simply by typing in text.  Ie the operation of the filter is independent of the button if desired. So I think the present situation is the correct one.  Open to persuasion though.

**Comment by richardjonesnz** [comment]
A further consideration might be installations that are not using the ATTO editor - they won't want the filter to be dependent on the button being installed.  Please close the issue if you are happy with my reasoning.

**Comment by mudrd8mz** [comment]
Sure, I never meant that the filter should declare dependency on the editor button.

**Comment by mudrd8mz** [comment]
Oh now I see there is a typo in the first comment - there should not be "in the filter" but "on the filter". Sorry.
